### ISSUE TITLE
Wishlist/TODO

### ISSUE THREAD

**Issue by betafcc** [betafcc/eos-bootstrapping#9]
- [ ] [Infinite Bash history](https://stackoverflow.com/a/19533853)
- [ ] Path setting centralization (as of today, I feel this is way superior than 'topical' path setting)
- [ ] Personal bin folder centralized
- [ ] Variable exporting centralization
- [ ] no aliases (and document the problems I'm having with them)
- [ ] .profile
- [ ] sh/bash and interactive/login shell conditionals indicated and organized
